# config/app.yml for rails-settings-cached
defaults: &defaults
  foo: "Foo"
  bar: 123
  email_name: 'wangxinyun0805@163.com'
  email_password: 'ZNTJJLRDHTIFFLXH'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
