development: &development
  adapter: mysql2
  encoding: utf8
  host: 47.103.90.59

  reconnect: false
  database: lab
  pool: 50
  username: root
  password: zhangrun

development:
  <<: *development

production:
  <<: *development
