development: &development
  adapter: mysql2
  encoding: utf8
  host: localhost

  reconnect: false
  database: lab
  pool: 5
  username: root
  password: zhangrun

development:
  <<: *development

production:
  <<: *development
